"""Formal Fire Rabbit Spark game templates for KUN-owned delivery work."""

from __future__ import annotations


def formal_game_ready_files() -> dict[str, str]:
    """Return a fuller game project template generated by KUN work items."""

    return {
        "package.json": _package_json(),
        "scripts/internal-test.mjs": _internal_test_script(),
        "scripts/user-sim.mjs": _user_sim_script(),
        "scripts/fun-playtest.mjs": _fun_playtest_script(),
        "src/types.ts": _types_ts(),
        "src/data/worlds.ts": _worlds_ts(),
        "src/engine/safety.ts": _safety_ts(),
        "src/engine/spark.ts": _spark_ts(),
        "src/engine/storage.ts": _storage_ts(),
        "src/App.tsx": _app_tsx(),
        "src/styles.css": _styles_css(),
        "README.md": _readme_md(),
    }


def _package_json() -> str:
    return """{
  "name": "huohutu-spark-official-game",
  "version": "1.0.0-formal.1",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "vite --host 0.0.0.0",
    "build": "tsc -b && vite build",
    "preview": "vite preview --host 0.0.0.0",
    "test:internal": "node scripts/internal-test.mjs",
    "test:user-sim": "node scripts/user-sim.mjs",
    "test:fun": "node scripts/fun-playtest.mjs",
    "cap:init": "cap init HuohutuSpark com.huohutu.spark --web-dir=dist",
    "cap:sync": "npm run build && cap sync"
  },
  "dependencies": {
    "@capacitor/cli": "^7.4.3",
    "@capacitor/core": "^7.4.3",
    "@types/react": "^19.2.2",
    "@types/react-dom": "^19.2.2",
    "@vitejs/plugin-react": "^5.0.4",
    "react": "^19.2.0",
    "react-dom": "^19.2.0",
    "typescript": "^5.9.3",
    "vite": "^7.1.11"
  },
  "overrides": {
    "rollup": "npm:@rollup/wasm-node@4.60.4"
  },
  "devDependencies": {}
}
"""


def _internal_test_script() -> str:
    return """import { existsSync, readFileSync } from "node:fs";

const requiredFiles = [
  "src/App.tsx",
  "src/data/worlds.ts",
  "src/engine/safety.ts",
  "src/engine/storage.ts",
  "docs/interaction-design.md",
  "docs/internal-playtest-plan.md"
];

for (const file of requiredFiles) {
  if (!existsSync(file)) throw new Error(`Missing required file: ${file}`);
}

const app = readFileSync("src/App.tsx", "utf8");
const worlds = readFileSync("src/data/worlds.ts", "utf8");
const styles = readFileSync("src/styles.css", "utf8");
const storage = readFileSync("src/engine/storage.ts", "utf8");
const packageJson = JSON.parse(readFileSync("package.json", "utf8"));

const checks = [
  ["formal package", packageJson.name === "huohutu-spark-official-game"],
  ["adventure map", app.includes("adventureMap") && app.includes("levelSelect")],
  ["moment-to-moment fun loop", app.includes("funLoop") && app.includes("comboMeter")],
  ["reward and retry feedback", app.includes("rewardBurst") && app.includes("blockedReason")],
  ["vibecoding studio", app.includes("vibeCodingStudio") && app.includes("AI导演")],
  ["simulated AI director creates playable cards", app.includes("directorQueue") && app.includes("灵感卡")],
  ["two worlds with quest depth", worlds.includes("rainbow-island") && worlds.includes("story-planet") && worlds.match(/quest-/g)?.length >= 6],
  ["tablet app shell", styles.includes(".tabletShell") && styles.includes(".stageArena")],
  ["parent value", app.includes("家长火花册") && app.includes("成长回放")],
  ["test lab", app.includes("内测实验室") && packageJson.scripts["test:fun"] === "node scripts/fun-playtest.mjs"],
  ["fresh formal storage", storage.includes("huohutu.spark.official.formal.v1")],
];

const failed = checks.filter(([, ok]) => !ok).map(([name]) => name);
if (failed.length) throw new Error(`Formal internal checks failed: ${failed.join(", ")}`);

console.log(JSON.stringify({ ok: true, checks: checks.map(([name]) => name) }, null, 2));
"""


def _user_sim_script() -> str:
    return """import { readFileSync } from "node:fs";

const app = readFileSync("src/App.tsx", "utf8");
const worlds = readFileSync("src/data/worlds.ts", "utf8");
const styles = readFileSync("src/styles.css", "utf8");

const checks = [
  ["child enters a real game surface", app.includes("开始今天的冒险") && app.includes("adventureMap")],
  ["can play without typing", app.includes("playAction(action)") && app.includes("actionCard")],
  ["player agency beyond one prompt", app.includes("levelSelect") && app.includes("activeQuest")],
  ["world visibly changes", app.includes("stageObject") && app.includes("unlockedObjects")],
  ["reward loop", app.includes("rewardBurst") && app.includes("星星奖励")],
  ["fail/retry loop", app.includes("blockedReason") && app.includes("还缺少")],
  ["vibecoding turns ideas into playable changes", app.includes("runDirectorIdea") && app.includes("directorQueue")],
  ["parent can understand value", app.includes("成长回放") && app.includes("Spark 能力线索")],
  ["tablet-first UI", styles.includes("min-height: calc(100vh - 82px)") && styles.includes(".actionGrid")],
  ["formal game is not MVP copy", !app.includes("可玩 MVP") && !app.includes("游戏化内测版")],
  ["campaign depth", worlds.match(/action-/g)?.length >= 16],
];

const failed = checks.filter(([, ok]) => !ok).map(([name]) => name);
if (failed.length) throw new Error(`Formal user simulation failed: ${failed.join(", ")}`);

console.log(JSON.stringify({
  ok: true,
  simulatedPersonas: ["child-player", "parent-reviewer", "vibecoding-creator", "internal-game-tester"],
  checks: checks.map(([name]) => name)
}, null, 2));
"""


def _fun_playtest_script() -> str:
    return """import { readFileSync } from "node:fs";

const app = readFileSync("src/App.tsx", "utf8");
const worlds = readFileSync("src/data/worlds.ts", "utf8");

const checks = [
  ["clear goal", app.includes("今天目标") && app.includes("完成条件")],
  ["choice pressure", worlds.includes("requires") && worlds.includes("grants")],
  ["feedback within one click", app.includes("latestActiveEvent")],
  ["progression", app.includes("xp") && app.includes("stars")],
  ["creator loop", app.includes("vibeCodingStudio")],
  ["playtest dashboard", app.includes("funPlaytestChecks")],
];

const failed = checks.filter(([, ok]) => !ok).map(([name]) => name);
if (failed.length) throw new Error(`Fun playtest failed: ${failed.join(", ")}`);

console.log(JSON.stringify({ ok: true, checks: checks.map(([name]) => name) }, null, 2));
"""


def _types_ts() -> str:
    return """export type AgeBand = "2-4" | "5-6" | "7-9";
export type WorldId = "rainbow-island" | "story-planet";
export type SparkKey = "expression" | "creativity" | "story" | "science" | "social" | "nature" | "aiCollaboration";
export type ActionKind = "collect" | "craft" | "help" | "ask" | "comfort" | "director";
export type Mode = "play" | "parent" | "lab";

export interface GameAction {
  id: string;
  title: string;
  kind: ActionKind;
  prompt: string;
  result: string;
  requires: string[];
  grants: string[];
  object: string;
  spark: SparkKey[];
  xp: number;
  fun: string;
}

export interface Quest {
  id: string;
  title: string;
  goal: string;
  finish: string;
  actionIds: string[];
}

export interface World {
  id: WorldId;
  name: string;
  tagline: string;
  companion: string;
  palette: { sky: string; ground: string; accent: string };
  startingObjects: string[];
  quests: Quest[];
  actions: GameAction[];
}

export interface WorldProgress {
  activeQuestId: string;
  inventory: string[];
  unlockedObjects: string[];
  completedActionIds: string[];
  completedQuestIds: string[];
  stars: number;
  xp: number;
  combo: number;
}

export interface SparkScores {
  expression: number;
  creativity: number;
  story: number;
  science: number;
  social: number;
  nature: number;
  aiCollaboration: number;
}

export interface GameEvent {
  id: string;
  at: string;
  worldId: WorldId;
  questId: string;
  actionId: string;
  childInput: string;
  result: string;
  spark: SparkKey[];
  grants: string[];
  objects: string[];
  blockedReason?: string;
}

export interface DirectorCard {
  id: string;
  idea: string;
  playableChange: string;
  grantedToken: string;
}

export interface GameState {
  activeWorldId: WorldId;
  ageBand: AgeBand;
  progress: Record<WorldId, WorldProgress>;
  sparkScores: SparkScores;
  events: GameEvent[];
  directorQueue: DirectorCard[];
  soundOn: boolean;
}
"""


def _worlds_ts() -> str:
    return """import type { GameAction, World, WorldId, WorldProgress } from "../types";

const rainbowActions: GameAction[] = [
  { id: "action-red-light", title: "追红色光点", kind: "collect", prompt: "我追到红色光点", result: "红色光点绕着孩子转了一圈，落进造物背包。", requires: [], grants: ["红色光点"], object: "红色光点", spark: ["expression", "nature"], xp: 8, fun: "收集" },
  { id: "action-star-shape", title: "拍星星形状", kind: "collect", prompt: "我拍到星星形状", result: "星星形状发出叮的一声，变成可合成材料。", requires: [], grants: ["星星形状"], object: "星星形状", spark: ["science", "creativity"], xp: 8, fun: "观察" },
  { id: "action-star-cloud", title: "合成星星云", kind: "craft", prompt: "合成星星云", result: "红色星星云升起来，照亮小兔看不见的路。", requires: ["红色光点", "星星形状"], grants: ["星星云"], object: "红色星星云", spark: ["creativity", "aiCollaboration"], xp: 16, fun: "合成" },
  { id: "action-bridge-base", title: "铺桥面", kind: "craft", prompt: "铺一段桥面", result: "第一段彩虹桥出现，河水开始变安静。", requires: ["红色光点"], grants: ["桥面"], object: "彩虹桥面", spark: ["science", "creativity"], xp: 14, fun: "建造" },
  { id: "action-rabbit-cross", title: "护送小兔", kind: "help", prompt: "护送小兔过桥", result: "小兔踩着桥面跳过去，送给孩子一颗勇气星。", requires: ["桥面", "星星云"], grants: ["勇气星"], object: "过桥小兔", spark: ["social", "story"], xp: 18, fun: "救援" },
  { id: "action-rainbow-festival", title: "点亮庆典", kind: "director", prompt: "让造物岛开庆典", result: "天空出现小小庆典，孩子的造物被挂到岛中央。", requires: ["勇气星"], grants: ["庆典徽章"], object: "造物庆典", spark: ["expression", "creativity", "aiCollaboration"], xp: 22, fun: "创造" },
  { id: "action-wind-seed", title: "种风种子", kind: "collect", prompt: "找一颗风种子", result: "风种子呼呼转起来，可以推动云朵。", requires: [], grants: ["风种子"], object: "风种子", spark: ["nature", "science"], xp: 10, fun: "探索" },
  { id: "action-cloud-race", title: "云朵竞速", kind: "help", prompt: "推云朵比赛", result: "云朵穿过彩虹门，打开隐藏奖励。", requires: ["风种子"], grants: ["彩虹门钥匙"], object: "彩虹门", spark: ["science", "story"], xp: 16, fun: "挑战" }
];

const storyActions: GameAction[] = [
  { id: "action-footprint", title: "找发光脚印", kind: "collect", prompt: "找发光脚印", result: "一串发光脚印指向问题之门。", requires: [], grants: ["发光脚印"], object: "发光脚印", spark: ["story", "science"], xp: 8, fun: "寻找" },
  { id: "action-question-door", title: "问问题之门", kind: "ask", prompt: "为什么星星会迷路", result: "问题之门被问醒了，吐出一把问题钥匙。", requires: ["发光脚印"], grants: ["问题钥匙"], object: "问题之门", spark: ["story", "aiCollaboration"], xp: 14, fun: "提问" },
  { id: "action-comfort-star", title: "安慰迷路星星", kind: "comfort", prompt: "星星别怕，我陪你", result: "迷路星星亮了一点，交给孩子一团友谊光。", requires: [], grants: ["友谊光"], object: "被安慰的星星", spark: ["social", "expression"], xp: 14, fun: "共情" },
  { id: "action-route-home", title: "点亮回家路线", kind: "help", prompt: "点亮回家路线", result: "问题钥匙和友谊光合在一起，变成一排星星路灯。", requires: ["问题钥匙", "友谊光"], grants: ["星路徽章"], object: "星星路灯", spark: ["story", "social", "creativity"], xp: 22, fun: "解谜" },
  { id: "action-bubble-ship", title: "修泡泡飞船", kind: "craft", prompt: "修泡泡飞船", result: "泡泡飞船鼓起来，带孩子飞到故事星云旁边。", requires: ["星路徽章"], grants: ["飞船票"], object: "泡泡飞船", spark: ["science", "story"], xp: 18, fun: "升级" },
  { id: "action-story-ending", title: "编结局", kind: "director", prompt: "我来编一个结局", result: "AI导演把孩子的结局变成可继续玩的故事舞台。", requires: ["飞船票"], grants: ["故事导演徽章"], object: "故事舞台", spark: ["expression", "story", "aiCollaboration"], xp: 24, fun: "共创" },
  { id: "action-moon-note", title: "听月亮便签", kind: "collect", prompt: "听月亮便签", result: "月亮留下一个轻轻的问题：朋友为什么重要？", requires: [], grants: ["月亮便签"], object: "月亮便签", spark: ["story", "social"], xp: 10, fun: "倾听" },
  { id: "action-friend-song", title: "唱朋友歌", kind: "comfort", prompt: "唱一首朋友歌", result: "朋友歌让星云变成温暖颜色。", requires: ["月亮便签"], grants: ["朋友旋律"], object: "朋友歌", spark: ["expression", "social"], xp: 16, fun: "表达" }
];

export const worlds: Record<WorldId, World> = {
  "rainbow-island": {
    id: "rainbow-island",
    name: "彩虹造物岛",
    tagline: "收集、合成、建造，帮助小兔回家。",
    companion: "小火",
    palette: { sky: "#8bd8ff", ground: "#8bdc91", accent: "#ff8c6a" },
    startingObjects: ["小兔", "造物台", "小河"],
    quests: [
      { id: "quest-rainbow-1", title: "星星云配方", goal: "收集两个材料并合成星星云。", finish: "做出星星云", actionIds: ["action-red-light", "action-star-shape", "action-star-cloud"] },
      { id: "quest-rainbow-2", title: "彩虹桥救援", goal: "铺桥面并护送小兔过河。", finish: "小兔安全过桥", actionIds: ["action-bridge-base", "action-rabbit-cross"] },
      { id: "quest-rainbow-3", title: "造物岛庆典", goal: "把救援成果变成庆典舞台。", finish: "庆典点亮", actionIds: ["action-rainbow-festival", "action-wind-seed", "action-cloud-race"] }
    ],
    actions: rainbowActions
  },
  "story-planet": {
    id: "story-planet",
    name: "故事星球",
    tagline: "找线索、问问题、安慰伙伴，点亮星星的回家路。",
    companion: "泡泡船长",
    palette: { sky: "#a996ff", ground: "#91d8c8", accent: "#ffd166" },
    startingObjects: ["泡泡飞船", "迷路星星", "问题之门"],
    quests: [
      { id: "quest-story-1", title: "问题之门", goal: "找到脚印并问出好问题。", finish: "拿到问题钥匙", actionIds: ["action-footprint", "action-question-door"] },
      { id: "quest-story-2", title: "星星回家", goal: "安慰星星并点亮路线。", finish: "星星路灯亮起", actionIds: ["action-comfort-star", "action-route-home"] },
      { id: "quest-story-3", title: "故事导演", goal: "修飞船，编结局，把故事变成新舞台。", finish: "故事舞台完成", actionIds: ["action-bubble-ship", "action-story-ending", "action-moon-note", "action-friend-song"] }
    ],
    actions: storyActions
  }
};

export function initialProgress(): Record<WorldId, WorldProgress> {
  return Object.fromEntries(Object.values(worlds).map((world) => [world.id, {
    activeQuestId: world.quests[0].id,
    inventory: [],
    unlockedObjects: [...world.startingObjects],
    completedActionIds: [],
    completedQuestIds: [],
    stars: 0,
    xp: 0,
    combo: 0
  }])) as unknown as Record<WorldId, WorldProgress>;
}
"""


def _safety_ts() -> str:
    return """export function sanitizeIdea(text: string): { safeText: string; redirected: boolean } {
  const unsafe = ["炸", "杀", "死", "打人", "毁掉", "血"];
  if (unsafe.some((word) => text.includes(word))) {
    return { safeText: "把危险想法改造成守护任务，让伙伴更安全", redirected: true };
  }
  return { safeText: text, redirected: false };
}
"""


def _spark_ts() -> str:
    return """import type { GameEvent, SparkKey, SparkScores } from "../types";

export const sparkLabels: Record<SparkKey, string> = {
  expression: "表达",
  creativity: "创造",
  story: "故事",
  science: "科学",
  social: "社交",
  nature: "自然",
  aiCollaboration: "AI协作"
};

export function summarizeSpark(events: GameEvent[], scores: SparkScores): string {
  const strongest = Object.entries(scores).sort((a, b) => b[1] - a[1])[0]?.[0] ?? "expression";
  return `最近 ${events.length} 个片段里，孩子最明显的火花是 ${sparkLabels[strongest as SparkKey]}。`;
}
"""


def _storage_ts() -> str:
    return """import { initialProgress } from "../data/worlds";
import type { GameState, SparkScores } from "../types";

const storageKey = "huohutu.spark.official.formal.v1";

export const zeroSpark: SparkScores = {
  expression: 0,
  creativity: 0,
  story: 0,
  science: 0,
  social: 0,
  nature: 0,
  aiCollaboration: 0
};

export function createGame(): GameState {
  return {
    activeWorldId: "rainbow-island",
    ageBand: "5-6",
    progress: initialProgress(),
    sparkScores: { ...zeroSpark },
    events: [],
    directorQueue: [],
    soundOn: true
  };
}

export function loadGame(): GameState {
  const raw = window.localStorage.getItem(storageKey);
  if (!raw) return createGame();
  try {
    const parsed = JSON.parse(raw) as GameState;
    if (!parsed.progress?.["rainbow-island"] || !parsed.progress?.["story-planet"]) return createGame();
    return parsed;
  } catch {
    return createGame();
  }
}

export function saveGame(state: GameState): void {
  window.localStorage.setItem(storageKey, JSON.stringify(state));
}

export function resetGame(): GameState {
  const next = createGame();
  saveGame(next);
  return next;
}
"""


def _app_tsx() -> str:
    return """import { useEffect, useMemo, useState } from "react";
import { worlds } from "./data/worlds";
import { sanitizeIdea } from "./engine/safety";
import { loadGame, resetGame, saveGame } from "./engine/storage";
import type { GameAction, GameEvent, GameState, Mode, SparkKey, WorldId } from "./types";
import "./styles.css";

const sparkLabels: Record<SparkKey, string> = {
  expression: "表达",
  creativity: "创造",
  story: "故事",
  science: "科学",
  social: "社交",
  nature: "自然",
  aiCollaboration: "AI协作"
};

const ideaChips = ["给小兔做云朵滑梯", "把星星路灯变成音乐", "让彩虹桥会唱歌"];

function unique(values: string[]): string[] {
  return [...new Set(values)];
}

function applySpark(state: GameState, keys: SparkKey[]): GameState["sparkScores"] {
  const next = { ...state.sparkScores };
  for (const key of keys) next[key] = Math.min(100, next[key] + 8);
  return next;
}

export default function App() {
  const [game, setGame] = useState<GameState>(() => loadGame());
  const [mode, setMode] = useState<Mode>("play");
  const [idea, setIdea] = useState("");
  const [rewardBurst, setRewardBurst] = useState("开始今天的冒险");

  useEffect(() => saveGame(game), [game]);

  const activeWorld = worlds[game.activeWorldId];
  const progress = game.progress[game.activeWorldId];
  const activeQuest = activeWorld.quests.find((quest) => quest.id === progress.activeQuestId) ?? activeWorld.quests[0];
  const activeQuestActions = activeQuest.actionIds.map((id) => activeWorld.actions.find((action) => action.id === id)).filter(Boolean) as GameAction[];
  const latestActiveEvent = game.events.find((event) => event.worldId === activeWorld.id);
  const questDoneCount = activeQuest.actionIds.filter((id) => progress.completedActionIds.includes(id)).length;
  const questPercent = Math.round((questDoneCount / activeQuest.actionIds.length) * 100);
  const totalStars = Object.values(game.progress).reduce((sum, item) => sum + item.stars, 0);
  const totalXp = Object.values(game.progress).reduce((sum, item) => sum + item.xp, 0);

  const funPlaytestChecks = [
    { label: "孩子不用打字也能玩", ok: game.events.some((event) => event.actionId.startsWith("action-")) },
    { label: "至少一次合成/建造", ok: game.events.some((event) => event.objects.length > 0) },
    { label: "出现星星奖励", ok: totalStars > 0 },
    { label: "两个世界都有进度", ok: new Set(game.events.map((event) => event.worldId)).size >= 2 },
    { label: "vibecoding 生成可玩变化", ok: game.directorQueue.length > 0 }
  ];

  function update(mutator: (current: GameState) => GameState) {
    setGame((current) => mutator(current));
  }

  function selectWorld(worldId: WorldId) {
    update((current) => ({ ...current, activeWorldId: worldId }));
  }

  function selectQuest(questId: string) {
    update((current) => {
      const currentProgress = current.progress[current.activeWorldId];
      return {
        ...current,
        progress: {
          ...current.progress,
          [current.activeWorldId]: { ...currentProgress, activeQuestId: questId }
        }
      };
    });
  }

  function playAction(action: GameAction) {
    update((current) => {
      const world = worlds[current.activeWorldId];
      const worldProgress = current.progress[world.id];
      const missing = action.requires.filter((token) => !worldProgress.inventory.includes(token));
      const blockedReason = missing.length ? `还缺少：${missing.join("、")}。先去收集或完成前置挑战。` : undefined;
      const completedActionIds = blockedReason ? worldProgress.completedActionIds : unique([...worldProgress.completedActionIds, action.id]);
      const inventory = blockedReason ? worldProgress.inventory : unique([...worldProgress.inventory, ...action.grants]);
      const unlockedObjects = blockedReason ? worldProgress.unlockedObjects : unique([...worldProgress.unlockedObjects, action.object]);
      const active = world.quests.find((quest) => quest.id === worldProgress.activeQuestId) ?? world.quests[0];
      const completedQuestIds = active.actionIds.every((id) => completedActionIds.includes(id))
        ? unique([...worldProgress.completedQuestIds, active.id])
        : worldProgress.completedQuestIds;
      const stars = completedQuestIds.includes(active.id) && !worldProgress.completedQuestIds.includes(active.id)
        ? worldProgress.stars + 1
        : worldProgress.stars;
      const event: GameEvent = {
        id: `event-${Date.now()}-${action.id}`,
        at: new Date().toISOString(),
        worldId: world.id,
        questId: active.id,
        actionId: action.id,
        childInput: action.prompt,
        result: blockedReason ?? action.result,
        spark: action.spark,
        grants: blockedReason ? [] : action.grants,
        objects: blockedReason ? [] : [action.object],
        blockedReason
      };
      setRewardBurst(blockedReason ? "再试一次" : `星星奖励 +${stars > worldProgress.stars ? 1 : 0} · ${action.fun}`);
      return {
        ...current,
        progress: {
          ...current.progress,
          [world.id]: {
            ...worldProgress,
            inventory,
            unlockedObjects,
            completedActionIds,
            completedQuestIds,
            stars,
            xp: blockedReason ? worldProgress.xp : worldProgress.xp + action.xp,
            combo: blockedReason ? 0 : worldProgress.combo + 1
          }
        },
        sparkScores: blockedReason ? current.sparkScores : applySpark(current, action.spark),
        events: [event, ...current.events].slice(0, 120)
      };
    });
  }

  function runDirectorIdea(text = idea) {
    const cleaned = sanitizeIdea(text.trim());
    if (!cleaned.safeText) return;
    update((current) => {
      const worldProgress = current.progress[current.activeWorldId];
      const token = `灵感卡-${current.directorQueue.length + 1}`;
      const object = `${cleaned.safeText.slice(0, 8)}造物`;
      const card = {
        id: `director-${Date.now()}`,
        idea: text,
        playableChange: `${cleaned.safeText}，已经变成下一轮可玩的舞台机关。`,
        grantedToken: token
      };
      const event: GameEvent = {
        id: `event-${Date.now()}-director`,
        at: new Date().toISOString(),
        worldId: current.activeWorldId,
        questId: worldProgress.activeQuestId,
        actionId: "director-card",
        childInput: cleaned.safeText,
        result: cleaned.redirected ? `安全改写：${card.playableChange}` : card.playableChange,
        spark: ["expression", "creativity", "aiCollaboration"],
        grants: [token],
        objects: [object]
      };
      setRewardBurst("AI导演生成了新机关");
      return {
        ...current,
        directorQueue: [card, ...current.directorQueue].slice(0, 8),
        progress: {
          ...current.progress,
          [current.activeWorldId]: {
            ...worldProgress,
            inventory: unique([...worldProgress.inventory, token]),
            unlockedObjects: unique([...worldProgress.unlockedObjects, object]),
            xp: worldProgress.xp + 12,
            combo: worldProgress.combo + 1
          }
        },
        sparkScores: applySpark(current, ["expression", "creativity", "aiCollaboration"]),
        events: [event, ...current.events].slice(0, 120)
      };
    });
    setIdea("");
  }

  const topSpark = useMemo(() => {
    return Object.entries(game.sparkScores).sort((a, b) => b[1] - a[1])[0] as [SparkKey, number];
  }, [game.sparkScores]);

  return (
    <main className="tabletShell">
      <header className="topBar">
        <div><strong>火火兔 Spark 正式游戏</strong><span>vibecoding 参考：说出想法，马上变成可玩的世界变化</span></div>
        <nav><button className={mode === "play" ? "on" : ""} onClick={() => setMode("play")}>进入游戏</button><button className={mode === "parent" ? "on" : ""} onClick={() => setMode("parent")}>家长火花册</button><button className={mode === "lab" ? "on" : ""} onClick={() => setMode("lab")}>内测实验室</button></nav>
      </header>

      {mode === "play" ? (
        <section className="gameScreen">
          <aside className="adventureMap">
            <h2>冒险地图</h2>
            {Object.values(worlds).map((world) => <button key={world.id} className={game.activeWorldId === world.id ? "selected" : ""} onClick={() => selectWorld(world.id)}><strong>{world.name}</strong><span>{world.tagline}</span></button>)}
            <h2>levelSelect</h2>
            {activeWorld.quests.map((quest) => <button key={quest.id} className={progress.activeQuestId === quest.id ? "selected" : ""} onClick={() => selectQuest(quest.id)}><strong>{quest.title}</strong><span>完成条件：{quest.finish}</span></button>)}
            <button className="reset" onClick={() => { setGame(resetGame()); setRewardBurst("重新开始今天的冒险"); }}>重置体验</button>
          </aside>

          <section className="funLoop">
            <div className="goalCard">
              <div><span>今天目标</span><h1>{activeQuest.goal}</h1><p>{activeWorld.companion}陪你玩 · 当前世界：{activeWorld.name}</p></div>
              <div className="comboMeter"><strong>{questPercent}%</strong><i><b style={{ width: `${questPercent}%` }} /></i><span>连击 {progress.combo} · 星星 {progress.stars} · XP {progress.xp}</span></div>
            </div>

            <section className="stageArena" style={{ "--sky": activeWorld.palette.sky, "--ground": activeWorld.palette.ground, "--accent": activeWorld.palette.accent } as React.CSSProperties}>
              <div className="sun" /><div className="ground" /><div className="portal" />
              {progress.unlockedObjects.map((object, index) => <button className={`stageObject o${(index % 8) + 1}`} key={`${object}-${index}`} onClick={() => playAction(activeQuestActions[Math.min(index, activeQuestActions.length - 1)] ?? activeWorld.actions[0])}>{object}</button>)}
              <article className="companion"><strong>{activeWorld.companion}</strong><span>{latestActiveEvent?.result ?? "点一张行动卡开始玩，世界会马上变化。"}</span></article>
              <div className="rewardBurst">{rewardBurst}</div>
            </section>

            <section className="inventory"><div><strong>背包</strong><span>{progress.inventory.length ? progress.inventory.join(" · ") : "先去收集材料"}</span></div><div><strong>成长</strong><span>总星星 {totalStars} · 总 XP {totalXp}</span></div></section>

            <section className="actionGrid">
              {activeQuestActions.map((action) => {
                const missing = action.requires.filter((token) => !progress.inventory.includes(token));
                const done = progress.completedActionIds.includes(action.id);
                const blockedReason = missing.length ? `还缺少 ${missing.join("、")}` : "";
                return <button className={`actionCard ${done ? "done" : ""}`} key={action.id} onClick={() => playAction(action)}><small>{action.fun}</small><strong>{action.title}</strong><span>{blockedReason || "可行动"}</span></button>;
              })}
            </section>

            <form className="vibeCodingStudio" onSubmit={(event) => { event.preventDefault(); runDirectorIdea(); }}>
              <div><strong>AI导演 vibecoding 工坊</strong><span>孩子说一个想法，系统生成可玩机关，不只是显示文字。</span></div>
              <div className="ideaChips">{ideaChips.map((chip) => <button type="button" key={chip} onClick={() => runDirectorIdea(chip)}>{chip}</button>)}</div>
              <label><input value={idea} onChange={(event) => setIdea(event.target.value)} placeholder="例如：让彩虹桥会唱歌" /><button type="submit">生成可玩变化</button></label>
            </form>
          </section>
        </section>
      ) : mode === "parent" ? (
        <section className="parentBook">
          <header><div><span>成长回放</span><h1>Spark 能力线索</h1></div><button onClick={() => update((current) => ({ ...current, soundOn: !current.soundOn }))}>{game.soundOn ? "声音开" : "声音关"}</button></header>
          <article className="summary"><h2>{sparkLabels[topSpark[0]]}最亮</h2><p>孩子已经完成 {game.events.length} 个游戏片段，获得 {totalStars} 颗星星。家长可以从片段里看到表达、共情、创造和 AI 协作线索。</p></article>
          <section className="sparkGrid">{Object.entries(game.sparkScores).map(([key, value]) => <div key={key}><span>{sparkLabels[key as SparkKey]}</span><meter min="0" max="100" value={value} /><strong>{value}</strong></div>)}</section>
          <section className="timeline">{game.events.slice(0, 10).map((event) => <article key={event.id}><strong>{worlds[event.worldId].name} · {event.childInput}</strong><p>{event.result}</p><small>{event.spark.map((key) => sparkLabels[key]).join(" · ")}</small></article>)}</section>
        </section>
      ) : (
        <section className="lab">
          <header><div><span>正式游戏门禁</span><h1>内测实验室</h1></div><button onClick={() => setGame(resetGame())}>清空重测</button></header>
          <section className="checks">{funPlaytestChecks.map((check) => <p className={check.ok ? "ok" : ""} key={check.label}>{check.ok ? "通过" : "待测"} · {check.label}</p>)}</section>
          <section className="timeline">{game.directorQueue.map((card) => <article key={card.id}><strong>灵感卡 · {card.grantedToken}</strong><p>{card.playableChange}</p></article>)}</section>
        </section>
      )}
    </main>
  );
}
"""


def _styles_css() -> str:
    return """:root { font-family: Inter, "PingFang SC", "Microsoft YaHei", system-ui, sans-serif; color: #18314a; background: #eef5fb; } * { box-sizing: border-box; } body { margin: 0; min-width: 320px; min-height: 100vh; } button, input { font: inherit; } button { cursor: pointer; }
.tabletShell { min-height: 100vh; display: grid; grid-template-rows: auto 1fr; }
.topBar { min-height: 82px; display: flex; align-items: center; justify-content: space-between; gap: 18px; padding: 16px 24px; background: #fff; border-bottom: 1px solid #d8e7f4; position: sticky; top: 0; z-index: 10; } .topBar strong, .topBar span { display: block; } .topBar strong { font-size: 21px; } .topBar span { color: #60758a; } .topBar nav { display: flex; gap: 8px; background: #edf5fb; padding: 5px; border-radius: 8px; } .topBar nav button { border: 0; border-radius: 7px; padding: 10px 14px; color: #52677c; background: transparent; font-weight: 900; } .topBar nav .on { background: #18314a; color: #fff; }
.gameScreen { display: grid; grid-template-columns: 310px minmax(0, 1fr); min-height: calc(100vh - 82px); }
.adventureMap { display: grid; align-content: start; gap: 12px; padding: 18px; background: #fff; border-right: 1px solid #d8e7f4; } .adventureMap h2 { margin: 12px 0 0; font-size: 14px; color: #698199; } .adventureMap button { border: 1px solid #d7e6f2; border-radius: 8px; background: #fff; padding: 12px; text-align: left; color: #18314a; } .adventureMap button strong, .adventureMap button span { display: block; } .adventureMap button span { color: #60758a; line-height: 1.4; margin-top: 4px; } .adventureMap .selected { border-color: #34bea8; background: #e9fbf6; } .adventureMap .reset { margin-top: 14px; text-align: center; background: #f5f8fc; }
.funLoop { padding: 20px; display: grid; gap: 15px; align-content: start; }
.goalCard, .inventory, .actionGrid, .vibeCodingStudio, .parentBook header, .summary, .sparkGrid, .timeline, .lab header, .checks { border: 1px solid #d7e6f2; border-radius: 8px; background: #fff; padding: 15px; }
.goalCard { display: flex; justify-content: space-between; gap: 16px; align-items: center; } .goalCard span, .goalCard p { color: #60758a; margin: 0; } .goalCard h1 { margin: 4px 0 6px; font-size: 25px; line-height: 1.16; } .comboMeter { min-width: 230px; display: grid; gap: 7px; } .comboMeter strong { font-size: 30px; } .comboMeter i { height: 14px; border-radius: 999px; background: #e4eef7; overflow: hidden; } .comboMeter b { display: block; height: 100%; background: linear-gradient(90deg, #34bea8, #ff8c6a); }
.stageArena { --sky: #8bd8ff; --ground: #8bdc91; --accent: #ff8c6a; min-height: 470px; position: relative; overflow: hidden; border: 1px solid rgba(24,49,74,.12); border-radius: 8px; background: linear-gradient(180deg, var(--sky) 0%, #f7fbff 62%, var(--ground) 63%, var(--ground) 100%); box-shadow: inset 0 -50px 100px rgba(24,49,74,.1); }
.sun, .ground, .portal, .stageObject, .companion, .rewardBurst { position: absolute; } .sun { right: 8%; top: 10%; width: 90px; height: 90px; border-radius: 50%; background: #ffd166; box-shadow: 0 0 0 18px rgba(255,209,102,.25); } .ground { left: -5%; right: -5%; bottom: -72px; height: 172px; border-radius: 55% 55% 0 0; background: rgba(255,255,255,.28); } .portal { left: 12%; top: 14%; width: 175px; height: 88px; border-radius: 999px; border: 14px solid rgba(255,255,255,.7); }
.stageObject { min-width: 94px; max-width: 150px; min-height: 54px; border: 2px solid rgba(24,49,74,.12); border-radius: 8px; background: rgba(255,255,255,.94); color: #18314a; font-weight: 900; box-shadow: 0 14px 30px rgba(24,49,74,.16); animation: bob 2.6s ease-in-out infinite; } .o1 { left: 10%; bottom: 82px; } .o2 { left: 29%; bottom: 138px; } .o3 { left: 50%; bottom: 96px; } .o4 { right: 13%; bottom: 154px; } .o5 { right: 8%; bottom: 74px; } .o6 { left: 17%; top: 114px; } .o7 { right: 30%; top: 96px; } .o8 { left: 43%; top: 172px; }
@keyframes bob { 0%, 100% { transform: translateY(0); } 50% { transform: translateY(-8px); } }
.companion { left: 24px; bottom: 24px; width: min(390px, calc(100% - 48px)); background: #18314a; color: #fff; border-radius: 8px; padding: 15px; box-shadow: 0 18px 36px rgba(24,49,74,.24); } .companion span { display: block; color: #d8eeff; line-height: 1.45; margin-top: 5px; } .rewardBurst { right: 22px; top: 22px; background: #fff7e6; color: #8a4a14; border: 1px solid #ffd28b; border-radius: 8px; padding: 12px 14px; font-weight: 900; }
.inventory { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; } .inventory strong, .inventory span { display: block; } .inventory span { color: #60758a; margin-top: 4px; }
.actionGrid { display: grid; grid-template-columns: repeat(4, minmax(150px, 1fr)); gap: 12px; } .actionCard { min-height: 126px; border: 1px solid #d7e6f2; border-radius: 8px; background: #fbfdff; color: #18314a; padding: 12px; display: grid; gap: 7px; text-align: left; align-content: start; } .actionCard small { color: #ff8c6a; font-weight: 900; } .actionCard strong { font-size: 17px; } .actionCard span { color: #60758a; } .actionCard.done { background: #ecfbf6; border-color: #34bea8; }
.vibeCodingStudio { display: grid; gap: 12px; background: #fffaf0; border-color: #ffdb9f; } .vibeCodingStudio strong, .vibeCodingStudio span { display: block; } .vibeCodingStudio span { color: #6a7890; margin-top: 3px; } .ideaChips { display: flex; flex-wrap: wrap; gap: 8px; } .ideaChips button, .vibeCodingStudio label button, .parentBook header button, .lab header button { border: 0; border-radius: 8px; background: #ff8c6a; color: #fff; padding: 11px 14px; font-weight: 900; } .vibeCodingStudio label { display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: 10px; } .vibeCodingStudio input { border: 1px solid #cbd9e7; border-radius: 8px; min-height: 46px; padding: 0 13px; }
.parentBook, .lab { padding: 22px; display: grid; gap: 15px; } .parentBook header, .lab header { display: flex; justify-content: space-between; align-items: center; gap: 16px; } .parentBook h1, .lab h1 { margin: 4px 0 0; font-size: 30px; } .parentBook span, .lab span { color: #60758a; }
.summary { background: #fff7e6; border-color: #ffd28b; } .sparkGrid { display: grid; gap: 10px; } .sparkGrid div { display: grid; grid-template-columns: 110px minmax(120px, 1fr) 48px; gap: 10px; align-items: center; } meter { width: 100%; height: 16px; }
.timeline { display: grid; gap: 10px; } .timeline article { border: 1px solid #e2edf6; border-radius: 8px; padding: 12px; background: #fbfdff; } .timeline p { margin: 8px 0; color: #3d5268; } .timeline small { color: #60758a; }
.checks { display: grid; gap: 8px; } .checks p { margin: 0; border: 1px solid #e1edf6; border-radius: 8px; padding: 10px; } .checks .ok { background: #ecfbf6; border-color: #34bea8; }
@media (max-width: 980px) { .gameScreen { grid-template-columns: 1fr; } .adventureMap { border-right: 0; border-bottom: 1px solid #d8e7f4; } .actionGrid { grid-template-columns: repeat(2, minmax(150px, 1fr)); } .topBar { align-items: stretch; flex-direction: column; } }
@media (max-width: 620px) { .funLoop, .parentBook, .lab, .adventureMap { padding: 14px; } .goalCard, .parentBook header, .lab header { align-items: stretch; flex-direction: column; } .inventory, .actionGrid, .vibeCodingStudio label, .sparkGrid div { grid-template-columns: 1fr; } .stageArena { min-height: 520px; } }
"""


def _readme_md() -> str:
    return """# 火火兔 Spark 正式游戏交付线

这个版本把当前任务从“可玩 MVP”升级为正式游戏方向：以好玩、可持续试玩、AI 导演共创和儿童成长记录为核心。

## 核心参考：vibecoding

- 用户用自然语言描述想法。
- AI 导演把想法变成可玩的机关、道具或关卡变化。
- 玩家马上试玩，用手感、反馈、奖励和复玩意愿判断好坏。
- KUN 持续根据试玩结果迭代，不把“代码生成完成”误当“游戏完成”。

## 运行

```bash
npm install
npm run dev -- --host 127.0.0.1 --port 5178
```

## 验收

```bash
npm run build
npm run test:internal
npm run test:user-sim
npm run test:fun
```
"""
