"""Gameful Fire Rabbit Spark MVP templates for the KUN game runner."""

from __future__ import annotations


def gameful_playtest_ready_files() -> dict[str, str]:
    """Return a game-first project template generated by KUN work items."""

    return {
        "package.json": _package_json(),
        "scripts/internal-test.mjs": _internal_test_script(),
        "scripts/user-sim.mjs": _user_sim_script(),
        "src/types.ts": _types_ts(),
        "src/data/worlds.ts": _worlds_ts(),
        "src/engine/safety.ts": _safety_ts(),
        "src/engine/spark.ts": _spark_ts(),
        "src/engine/storage.ts": _storage_ts(),
        "src/App.tsx": _app_tsx(),
        "src/styles.css": _styles_css(),
        "README.md": _readme_md(),
    }


def _package_json() -> str:
    return """{
  "name": "huohutu-spark-gameful-playtest",
  "version": "0.4.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "vite --host 0.0.0.0",
    "build": "tsc -b && vite build",
    "preview": "vite preview --host 0.0.0.0",
    "test:internal": "node scripts/internal-test.mjs",
    "test:user-sim": "node scripts/user-sim.mjs",
    "cap:init": "cap init HuohutuSpark com.huohutu.spark --web-dir=dist",
    "cap:sync": "npm run build && cap sync"
  },
  "dependencies": {
    "@capacitor/cli": "^7.4.3",
    "@capacitor/core": "^7.4.3",
    "@types/react": "^19.2.2",
    "@types/react-dom": "^19.2.2",
    "@vitejs/plugin-react": "^5.0.4",
    "react": "^19.2.0",
    "react-dom": "^19.2.0",
    "typescript": "^5.9.3",
    "vite": "^7.1.11"
  },
  "overrides": {
    "rollup": "npm:@rollup/wasm-node@4.60.4"
  },
  "devDependencies": {}
}
"""


def _internal_test_script() -> str:
    return """import { readFileSync, existsSync } from "node:fs";

const requiredFiles = [
  "src/App.tsx",
  "src/data/worlds.ts",
  "src/engine/safety.ts",
  "src/engine/spark.ts",
  "src/engine/storage.ts",
  "docs/interaction-design.md",
  "docs/internal-playtest-plan.md",
];

for (const file of requiredFiles) {
  if (!existsSync(file)) throw new Error(`Missing required file: ${file}`);
}

const app = readFileSync("src/App.tsx", "utf8");
const worlds = readFileSync("src/data/worlds.ts", "utf8");
const storage = readFileSync("src/engine/storage.ts", "utf8");
const packageJson = JSON.parse(readFileSync("package.json", "utf8"));

const checks = [
  ["gameful package", packageJson.name === "huohutu-spark-gameful-playtest"],
  ["game board", app.includes("gameBoard") && app.includes("worldStage")],
  ["action cards", app.includes("actionCard") && app.includes("playMove")],
  ["inventory tokens", app.includes("tokenShelf") && app.includes("progress.tokens")],
  ["quest progress", app.includes("questMeter") && app.includes("questProgress")],
  ["crafting mechanic", worlds.includes("requiredTokens") && worlds.includes("addsObjects")],
  ["not text echo demo", !app.includes("把孩子的词语变成")],
  ["parent spark book", app.includes("家长火花册")],
  ["internal game route", app.includes("游戏性内测")],
  ["safety redirect", app.includes("安全重定向")],
  ["user simulation script", packageJson.scripts["test:user-sim"] === "node scripts/user-sim.mjs"],
  ["world-specific feedback", app.includes("latestActiveWorldEvent") && app.includes("activeWorldEvents")],
  ["fresh storage namespace", storage.includes("huohutu.spark.gameful.snapshot.v4")],
];

const failed = checks.filter(([, ok]) => !ok).map(([name]) => name);
if (failed.length) throw new Error(`Internal game checks failed: ${failed.join(", ")}`);

console.log(JSON.stringify({ ok: true, checks: checks.map(([name]) => name) }, null, 2));
"""


def _user_sim_script() -> str:
    return """import { readFileSync } from "node:fs";

const app = readFileSync("src/App.tsx", "utf8");
const worlds = readFileSync("src/data/worlds.ts", "utf8");
const styles = readFileSync("src/styles.css", "utf8");

const checks = [
  ["first-run game goal", app.includes("今天的目标") && app.includes("开始冒险")],
  ["child can play without typing", app.includes("playMove(move)")],
  ["visible world changes", app.includes("stageObject") && app.includes("unlockedObjects")],
  ["success and blocked feedback", app.includes("还差") && app.includes("完成")],
  ["two different game loops", worlds.includes("彩虹造物岛") && worlds.includes("故事星球")],
  ["collection loop", worlds.includes("addsTokens")],
  ["craft loop", worlds.includes("requiredTokens")],
  ["quest win state", app.includes("任务完成") && app.includes("下一步")],
  ["parent value beyond chart", app.includes("阶段性纪念") && app.includes("孩子的火花线索")],
  ["large tablet-first board", styles.includes(".worldStage") && styles.includes(".actionDock")],
  ["internal tester can run scenarios", app.includes("runScenario") && app.includes("gameplayChecks")],
  ["world switch does not leak stale feedback", app.includes("activeWorldEvents") && app.includes("latestActiveWorldEvent")],
];

const failed = checks.filter(([, ok]) => !ok).map(([name]) => name);
if (failed.length) throw new Error(`User simulation checks failed: ${failed.join(", ")}`);

console.log(JSON.stringify({ ok: true, simulatedPersonas: ["new-child-player", "parent-reviewer", "internal-game-tester"], checks: checks.map(([name]) => name) }, null, 2));
"""


def _types_ts() -> str:
    return """export type AgeBand = "2-4" | "5-6" | "7-9";
export type SparkKey = "expression" | "creativity" | "story" | "science" | "social" | "nature" | "aiCollaboration";
export type WorldId = "rainbow-island" | "story-planet";
export type MoveKind = "collect" | "craft" | "help" | "ask" | "comfort" | "free";
export type SafetyLevel = "safe" | "redirected";

export interface GameMove {
  id: string;
  title: string;
  kind: MoveKind;
  phrase: string;
  result: string;
  requiredTokens: string[];
  addsTokens: string[];
  addsObjects: string[];
  sparkTags: SparkKey[];
  questDelta: number;
}

export interface WorldDefinition {
  id: WorldId;
  name: string;
  shortName: string;
  gameGoal: string;
  companion: string;
  companionRole: string;
  palette: { sky: string; ground: string; accent: string; ink: string };
  startingObjects: string[];
  moves: GameMove[];
  playtestScenarioIds: string[];
  sparkBias: SparkKey[];
}

export interface GameProgress {
  questProgress: number;
  tokens: string[];
  unlockedObjects: string[];
  completedMoveIds: string[];
  badges: string[];
}

export interface SparkScores {
  expression: number;
  creativity: number;
  story: number;
  science: number;
  social: number;
  nature: number;
  aiCollaboration: number;
}

export interface ChildEvent {
  id: string;
  at: string;
  worldId: WorldId;
  ageBand: AgeBand;
  moveId: string;
  childInput: string;
  result: string;
  safetyLevel: SafetyLevel;
  sparkTags: SparkKey[];
  tokens: string[];
  objects: string[];
}

export interface GameSnapshot {
  activeWorldId: WorldId;
  ageBand: AgeBand;
  progress: Record<WorldId, GameProgress>;
  sparkScores: SparkScores;
  events: ChildEvent[];
  cloudSyncEnabled: boolean;
}
"""


def _worlds_ts() -> str:
    return """import type { GameMove, GameProgress, WorldDefinition, WorldId } from "../types";

const rainbowMoves: GameMove[] = [
  { id: "catch-red-light", title: "收集红色光点", kind: "collect", phrase: "我找到红色光点", result: "红色光点跳进了造物台，天空出现一圈暖光。", requiredTokens: [], addsTokens: ["红色光点"], addsObjects: [], sparkTags: ["expression", "creativity"], questDelta: 1 },
  { id: "catch-star-shape", title: "收集星星形状", kind: "collect", phrase: "我找到星星形状", result: "星星形状落在小火手里，可以和颜色合成新东西。", requiredTokens: [], addsTokens: ["星星形状"], addsObjects: [], sparkTags: ["creativity", "science"], questDelta: 1 },
  { id: "craft-star-cloud", title: "合成星星云", kind: "craft", phrase: "把红色光点和星星形状合成云", result: "一朵红色星星云真的飘起来了，小兔看见了回家的方向。", requiredTokens: ["红色光点", "星星形状"], addsTokens: [], addsObjects: ["红色星星云"], sparkTags: ["creativity", "aiCollaboration", "nature"], questDelta: 2 },
  { id: "build-rainbow-bridge", title: "搭彩虹桥", kind: "help", phrase: "给小兔搭一座彩虹桥", result: "彩虹桥铺到河对岸，小兔向孩子挥手。", requiredTokens: ["红色光点"], addsTokens: ["桥梁徽章"], addsObjects: ["彩虹桥"], sparkTags: ["science", "social", "creativity"], questDelta: 2 },
  { id: "unsafe-redirect", title: "危险想法重定向", kind: "free", phrase: "我想炸掉小桥", result: "安全重定向：小火把危险想法变成修桥任务。桥被加固，伙伴更安心。", requiredTokens: [], addsTokens: ["守护徽章"], addsObjects: ["安全护栏"], sparkTags: ["expression", "aiCollaboration", "social"], questDelta: 1 },
];

const storyMoves: GameMove[] = [
  { id: "find-star-clue", title: "寻找星星线索", kind: "collect", phrase: "我寻找迷路星星的线索", result: "泡泡船长发现一枚发光脚印，故事地图打开了第一格。", requiredTokens: [], addsTokens: ["发光脚印"], addsObjects: ["线索光点"], sparkTags: ["story", "science"], questDelta: 1 },
  { id: "ask-why-door", title: "问问题之门", kind: "ask", phrase: "为什么星星会迷路", result: "问题之门亮起来：它想知道朋友在哪里，也想知道自己是谁。", requiredTokens: ["发光脚印"], addsTokens: ["问题钥匙"], addsObjects: ["问题之门"], sparkTags: ["science", "expression", "story"], questDelta: 2 },
  { id: "comfort-lost-star", title: "安慰迷路星星", kind: "comfort", phrase: "星星别怕，我们陪你找朋友", result: "迷路星星不再哭了，它愿意跟着孩子继续走。", requiredTokens: [], addsTokens: ["友谊光"], addsObjects: ["微笑星星"], sparkTags: ["social", "story", "expression"], questDelta: 2 },
  { id: "light-home-route", title: "点亮回家路线", kind: "help", phrase: "用问题钥匙和友谊光点亮路线", result: "回家的星路被点亮，泡泡船长把这段冒险收进绘本。", requiredTokens: ["问题钥匙", "友谊光"], addsTokens: ["故事徽章"], addsObjects: ["回家星路"], sparkTags: ["story", "aiCollaboration", "social"], questDelta: 3 },
];

export const worlds: Record<WorldId, WorldDefinition> = {
  "rainbow-island": {
    id: "rainbow-island",
    name: "彩虹造物岛",
    shortName: "造物岛",
    gameGoal: "收集颜色与形状，合成道具，帮助小兔过桥回家。",
    companion: "小火",
    companionRole: "造物台守护者",
    palette: { sky: "#8bd8ff", ground: "#95d987", accent: "#ff8c6a", ink: "#17324d" },
    startingObjects: ["小兔", "小河", "造物台"],
    moves: rainbowMoves,
    playtestScenarioIds: ["catch-red-light", "catch-star-shape", "craft-star-cloud", "build-rainbow-bridge", "unsafe-redirect"],
    sparkBias: ["expression", "creativity", "nature"],
  },
  "story-planet": {
    id: "story-planet",
    name: "故事星球",
    shortName: "故事星",
    gameGoal: "收集线索、提问、安慰伙伴，点亮迷路星星的回家路线。",
    companion: "泡泡船长",
    companionRole: "故事地图领航员",
    palette: { sky: "#9aa8ff", ground: "#ffd166", accent: "#43c5b8", ink: "#211b44" },
    startingObjects: ["泡泡飞船", "迷路星星", "关闭的问题之门"],
    moves: storyMoves,
    playtestScenarioIds: ["find-star-clue", "ask-why-door", "comfort-lost-star", "light-home-route"],
    sparkBias: ["story", "social", "aiCollaboration"],
  },
};

export const initialProgress: Record<WorldId, GameProgress> = {
  "rainbow-island": { questProgress: 0, tokens: [], unlockedObjects: ["小兔", "小河", "造物台"], completedMoveIds: [], badges: [] },
  "story-planet": { questProgress: 0, tokens: [], unlockedObjects: ["泡泡飞船", "迷路星星", "关闭的问题之门"], completedMoveIds: [], badges: [] },
};
"""


def _safety_ts() -> str:
    return """import type { SafetyLevel } from "../types";

const blockedTerms = ["打人", "伤害", "杀", "血", "危险", "跳楼", "自杀", "炸", "毒", "裸", "枪"];

export function classifySafety(input: string): { level: SafetyLevel; reason: string } {
  const normalized = input.trim().toLowerCase();
  const blocked = blockedTerms.find((term) => normalized.includes(term));
  return blocked ? { level: "redirected", reason: blocked } : { level: "safe", reason: "" };
}
"""


def _spark_ts() -> str:
    return """import type { ChildEvent, SparkKey, SparkScores } from "../types";

export const sparkLabels: Record<SparkKey, string> = {
  expression: "表达火花",
  creativity: "创造火花",
  story: "故事火花",
  science: "探索火花",
  social: "共情火花",
  nature: "自然火花",
  aiCollaboration: "AI协作火花",
};

export const initialSparkScores: SparkScores = { expression: 4, creativity: 4, story: 4, science: 4, social: 4, nature: 4, aiCollaboration: 4 };

export function applySpark(scores: SparkScores, tags: SparkKey[]): SparkScores {
  const next = { ...scores };
  for (const tag of tags) next[tag] = Math.min(100, next[tag] + 9);
  return next;
}

export function topSpark(scores: SparkScores): SparkKey {
  return (Object.keys(scores) as SparkKey[]).sort((a, b) => scores[b] - scores[a])[0];
}

export function summarizeSpark(events: ChildEvent[], scores: SparkScores): string {
  if (events.length === 0) return "还没有开始冒险。等孩子收集、合成或帮助伙伴后，这里会生成孩子的火花线索。";
  const recentTags = events.slice(0, 5).flatMap((event) => event.sparkTags);
  const top = sparkLabels[topSpark(scores)];
  const hints = [
    `${top}目前最亮。`,
    recentTags.includes("creativity") ? "孩子喜欢把材料组合成新物体，适合继续给造物挑战。" : "",
    recentTags.includes("science") ? "孩子会被规则和因果吸引，适合加入更多问题门。" : "",
    recentTags.includes("social") ? "孩子愿意照顾角色，适合加入协作和情绪任务。" : "",
    recentTags.includes("story") ? "孩子能把线索连成故事，适合生成阶段性纪念绘本。" : "",
  ].filter(Boolean);
  return hints.join(" ");
}
"""


def _storage_ts() -> str:
    return """import { initialProgress } from "../data/worlds";
import type { GameSnapshot } from "../types";
import { initialSparkScores } from "./spark";

const storageKey = "huohutu.spark.gameful.snapshot.v4";

function cloneProgress() {
  return structuredClone(initialProgress);
}

export function createInitialSnapshot(): GameSnapshot {
  return { activeWorldId: "rainbow-island", ageBand: "5-6", progress: cloneProgress(), sparkScores: initialSparkScores, events: [], cloudSyncEnabled: false };
}

export function loadSnapshot(): GameSnapshot {
  try {
    const raw = window.localStorage.getItem(storageKey);
    return raw ? { ...createInitialSnapshot(), ...JSON.parse(raw) } as GameSnapshot : createInitialSnapshot();
  } catch {
    return createInitialSnapshot();
  }
}

export function saveSnapshot(snapshot: GameSnapshot): void { window.localStorage.setItem(storageKey, JSON.stringify(snapshot)); }
export function resetSnapshot(): GameSnapshot { const next = createInitialSnapshot(); saveSnapshot(next); return next; }

export async function syncToCloudAdapter(snapshot: GameSnapshot): Promise<{ ok: boolean; message: string }> {
  if (!snapshot.cloudSyncEnabled) return { ok: true, message: "当前只保存在本机。真实儿童云端同步需要家长确认后再开启。" };
  await new Promise((resolve) => window.setTimeout(resolve, 180));
  return { ok: true, message: `已把 ${snapshot.events.length} 条游戏行为放入云端同步队列。MVP 当前使用模拟接口。` };
}
"""


def _app_tsx() -> str:
    return """import { useEffect, useMemo, useState } from "react";
import { initialProgress, worlds } from "./data/worlds";
import { classifySafety } from "./engine/safety";
import { applySpark, sparkLabels, summarizeSpark, topSpark } from "./engine/spark";
import { loadSnapshot, resetSnapshot, saveSnapshot, syncToCloudAdapter } from "./engine/storage";
import type { AgeBand, ChildEvent, GameMove, GameSnapshot, SparkKey, WorldId } from "./types";

const ageBands: Array<{ id: AgeBand; label: string; note: string }> = [
  { id: "2-4", label: "2-4岁", note: "点选与短句" },
  { id: "5-6", label: "5-6岁", note: "任务与合成" },
  { id: "7-9", label: "7-9岁", note: "规则与共创" },
];
const sparkOrder: SparkKey[] = ["expression", "creativity", "story", "science", "social", "nature", "aiCollaboration"];

function questPercent(value: number): number {
  return Math.min(100, Math.round((value / 6) * 100));
}

function unique(values: string[]): string[] {
  return Array.from(new Set(values));
}

export default function App() {
  const [snapshot, setSnapshot] = useState<GameSnapshot>(() => loadSnapshot());
  const [mode, setMode] = useState<"play" | "parent" | "test">("play");
  const [freeText, setFreeText] = useState("");
  const [syncMessage, setSyncMessage] = useState("当前只保存在本机");
  useEffect(() => saveSnapshot(snapshot), [snapshot]);

  const activeWorld = worlds[snapshot.activeWorldId];
  const progress = snapshot.progress[snapshot.activeWorldId];
  const activeWorldEvents = snapshot.events.filter((event) => event.worldId === activeWorld.id);
  const latestActiveWorldEvent = activeWorldEvents[0];
  const hasStarted = activeWorldEvents.length > 0;
  const topSparkKey = topSpark(snapshot.sparkScores);
  const gameplayChecks = [
    { label: "完成一次收集", ok: snapshot.events.some((event) => event.tokens.length > 0) },
    { label: "完成一次合成或建造", ok: snapshot.events.some((event) => event.objects.length > 0) },
    { label: "两个世界都被玩过", ok: new Set(snapshot.events.map((event) => event.worldId)).size >= 2 },
    { label: "触发安全重定向", ok: snapshot.events.some((event) => event.safetyLevel === "redirected") },
    { label: "任一世界任务完成", ok: Object.values(snapshot.progress).some((item) => item.questProgress >= 6) },
  ];
  const activeMoves = useMemo(() => activeWorld.moves, [activeWorld]);

  function updateSnapshot(mutator: (current: GameSnapshot) => GameSnapshot) {
    setSnapshot((current) => mutator(current));
  }

  function playMove(move: GameMove) {
    const safety = classifySafety(move.phrase);
    updateSnapshot((current) => {
      const worldProgress = current.progress[activeWorld.id];
      const missing = move.requiredTokens.filter((token) => !worldProgress.tokens.includes(token));
      const blocked = missing.length > 0 && safety.level === "safe";
      const tokens = blocked ? worldProgress.tokens : unique([...worldProgress.tokens, ...move.addsTokens]);
      const objects = blocked ? worldProgress.unlockedObjects : unique([...worldProgress.unlockedObjects, ...move.addsObjects]);
      const completedMoveIds = blocked ? worldProgress.completedMoveIds : unique([...worldProgress.completedMoveIds, move.id]);
      const questProgress = blocked ? worldProgress.questProgress : Math.min(6, worldProgress.questProgress + move.questDelta);
      const badges = questProgress >= 6 ? unique([...worldProgress.badges, `${activeWorld.shortName}任务完成`]) : worldProgress.badges;
      const result = blocked ? `还差 ${missing.join("、")}。先去收集材料，再回到这里合成。` : safety.level === "redirected" ? move.result : `${move.result} 任务进度增加了。`;
      const event: ChildEvent = { id: `event-${Date.now()}-${move.id}`, at: new Date().toISOString(), worldId: activeWorld.id, ageBand: current.ageBand, moveId: move.id, childInput: move.phrase, result, safetyLevel: safety.level, sparkTags: move.sparkTags, tokens: move.addsTokens, objects: move.addsObjects };
      return {
        ...current,
        progress: { ...current.progress, [activeWorld.id]: { ...worldProgress, tokens, unlockedObjects: objects, completedMoveIds, questProgress, badges } },
        sparkScores: applySpark(current.sparkScores, move.sparkTags),
        events: [event, ...current.events].slice(0, 100),
      };
    });
  }

  function playFreeText() {
    const text = freeText.trim();
    if (!text) return;
    const move: GameMove = { id: `free-${Date.now()}`, title: "自由创造", kind: "free", phrase: text, result: `AI导演把这句话变成了新的可玩物件：${text.slice(0, 8)}。`, requiredTokens: [], addsTokens: ["想法光点"], addsObjects: [`${text.slice(0, 6)}造物`], sparkTags: ["expression", "creativity", "aiCollaboration"], questDelta: 1 };
    playMove(move);
    setFreeText("");
  }

  function runScenario(moveId: string) {
    const move = Object.values(worlds).flatMap((world) => world.moves).find((item) => item.id === moveId);
    const world = Object.values(worlds).find((item) => item.moves.some((candidate) => candidate.id === moveId));
    if (!move || !world) return;
    updateSnapshot((current) => ({ ...current, activeWorldId: world.id }));
    window.setTimeout(() => playMove(move), 0);
    setMode("play");
  }

  function resetExperience() {
    setSnapshot({ ...resetSnapshot(), progress: structuredClone(initialProgress) });
    setMode("play");
  }

  async function handleCloudSync() {
    const next = { ...snapshot, cloudSyncEnabled: !snapshot.cloudSyncEnabled };
    setSnapshot(next);
    setSyncMessage((await syncToCloudAdapter(next)).message);
  }

  return (
    <main className="gameShell">
      <header className="topHud">
        <div><strong>火火兔 Spark</strong><span>孩子的第一个 AI 创造世界</span></div>
        <nav><button className={mode === "play" ? "active" : ""} onClick={() => setMode("play")}>进入游戏</button><button className={mode === "parent" ? "active" : ""} onClick={() => setMode("parent")}>家长火花册</button><button className={mode === "test" ? "active" : ""} onClick={() => setMode("test")}>游戏性内测</button></nav>
      </header>

      {mode === "play" ? (
        <section className="gameBoard">
          <aside className="worldPicker">
            <h2>选择世界</h2>
            {(Object.keys(worlds) as WorldId[]).map((worldId) => <button key={worldId} className={snapshot.activeWorldId === worldId ? "selected" : ""} onClick={() => updateSnapshot((current) => ({ ...current, activeWorldId: worldId }))}><strong>{worlds[worldId].name}</strong><span>{worlds[worldId].gameGoal}</span></button>)}
            <h2>年龄</h2>
            {ageBands.map((age) => <button key={age.id} className={snapshot.ageBand === age.id ? "selected small" : "small"} onClick={() => updateSnapshot((current) => ({ ...current, ageBand: age.id }))}>{age.label}<span>{age.note}</span></button>)}
            <button className="resetButton" onClick={resetExperience}>重置本机体验</button>
          </aside>

          <section className="playColumn">
            <div className="questBanner">
              <div><span>今天的目标</span><h1>{activeWorld.gameGoal}</h1><p>{activeWorld.companion} · {activeWorld.companionRole}</p></div>
              <div className="questMeter"><strong>{questPercent(progress.questProgress)}%</strong><div><i style={{ width: `${questPercent(progress.questProgress)}%` }} /></div><span>{progress.questProgress >= 6 ? "任务完成 · 下一步去家长火花册生成纪念" : "下一步：收集材料或完成行动卡"}</span></div>
            </div>

            {!hasStarted ? <div className="firstRunCoach"><strong>开始冒险</strong><p>点下面的行动卡，不用先打字。收集材料、合成物件、帮助角色，世界会真的变化。</p><button onClick={() => playMove(activeMoves[0])}>玩第一步</button></div> : null}

            <div className="worldStage" style={{ "--sky": activeWorld.palette.sky, "--ground": activeWorld.palette.ground, "--accent": activeWorld.palette.accent } as React.CSSProperties}>
              <div className="skyOrb" /><div className="stageGround" /><div className="portalRing" />
              {progress.unlockedObjects.map((object, index) => <button className={`stageObject object${(index % 6) + 1}`} key={`${object}-${index}`} onClick={() => playMove(activeMoves[Math.min(index, activeMoves.length - 1)])}>{object}</button>)}
              <div className="companionCard"><strong>{activeWorld.companion}</strong><span>{latestActiveWorldEvent?.result ?? "等你点一张行动卡。"}</span></div>
            </div>

            <section className="tokenShelf"><div><strong>收集物</strong><span>{progress.tokens.length ? progress.tokens.join(" · ") : "还没有材料"}</span></div><div><strong>徽章</strong><span>{progress.badges.length ? progress.badges.join(" · ") : "完成任务后出现"}</span></div></section>

            <section className="actionDock">
              {activeMoves.map((move) => <button className="actionCard" key={move.id} onClick={() => playMove(move)}><small>{move.kind}</small><strong>{move.title}</strong><span>{move.requiredTokens.length ? `需要：${move.requiredTokens.join("、")}` : "可直接行动"}</span></button>)}
            </section>

            <form className="directorInput" onSubmit={(event) => { event.preventDefault(); playFreeText(); }}>
              <input value={freeText} onChange={(event) => setFreeText(event.target.value)} placeholder="自由创造：例如 给小兔设计一艘云朵船" />
              <button type="submit">交给 AI导演</button>
            </form>
          </section>
        </section>
      ) : mode === "parent" ? (
        <section className="parentBook">
          <header><div><span>阶段性纪念</span><h1>孩子的火花线索</h1></div><button onClick={handleCloudSync}>{snapshot.cloudSyncEnabled ? "关闭云端队列" : "开启云端队列"}</button></header>
          <article className="keepsake"><h2>{sparkLabels[topSparkKey]}</h2><p>{summarizeSpark(snapshot.events, snapshot.sparkScores)}</p><small>{syncMessage}</small></article>
          <section className="sparkGrid">{sparkOrder.map((key) => <div key={key}><span>{sparkLabels[key]}</span><meter min="0" max="100" value={snapshot.sparkScores[key]} /><strong>{snapshot.sparkScores[key]}</strong></div>)}</section>
          <section className="timeline"><h2>最近游戏片段</h2>{snapshot.events.length === 0 ? <p className="empty">还没有记录。孩子完成收集、合成、帮助或提问后，这里会生成可给家长看的成长片段。</p> : snapshot.events.slice(0, 8).map((event) => <article key={event.id}><strong>{worlds[event.worldId].shortName} · {event.childInput}</strong><p>{event.result}</p><small>{event.sparkTags.map((tag) => sparkLabels[tag]).join(" · ")}</small></article>)}</section>
        </section>
      ) : (
        <section className="testMode">
          <header><div><span>不是脚本过场</span><h1>游戏性内测</h1></div><button onClick={resetExperience}>清空后重测</button></header>
          <section className="scenarioGrid">{Object.values(worlds).flatMap((world) => world.playtestScenarioIds.map((moveId) => ({ world, move: world.moves.find((item) => item.id === moveId)! }))).map(({ world, move }) => <article key={move.id}><strong>{world.shortName} · {move.title}</strong><p>{move.result}</p><button onClick={() => runScenario(move.id)}>跑这条</button></article>)}</section>
          <section className="gameplayChecks"><h2>游戏性通过项</h2><span>{gameplayChecks.filter((check) => check.ok).length}/{gameplayChecks.length}</span>{gameplayChecks.map((check) => <p className={check.ok ? "ok" : ""} key={check.label}>{check.ok ? "通过" : "待测"} · {check.label}</p>)}</section>
        </section>
      )}
    </main>
  );
}
"""


def _styles_css() -> str:
    return """:root { font-family: Inter, "PingFang SC", "Microsoft YaHei", system-ui, sans-serif; color: #1a2d3d; background: #f5f8fc; } * { box-sizing: border-box; } body { margin: 0; min-width: 320px; min-height: 100vh; } button, input { font: inherit; } button { cursor: pointer; }
.gameShell { min-height: 100vh; display: grid; grid-template-rows: auto 1fr; }
.topHud { min-height: 76px; display: flex; align-items: center; justify-content: space-between; gap: 18px; padding: 16px 24px; background: #fff; border-bottom: 1px solid #dce8f3; position: sticky; top: 0; z-index: 5; } .topHud strong, .topHud span { display: block; } .topHud strong { font-size: 21px; } .topHud span { color: #64788d; } .topHud nav { display: flex; gap: 8px; padding: 5px; border-radius: 8px; background: #edf4fb; } .topHud nav button { border: 0; border-radius: 7px; padding: 11px 15px; background: transparent; color: #52677c; font-weight: 900; } .topHud nav .active { background: #17324d; color: #fff; }
.gameBoard { display: grid; grid-template-columns: 300px minmax(0, 1fr); min-height: calc(100vh - 76px); }
.worldPicker { padding: 20px; background: #fff; border-right: 1px solid #dce8f3; display: flex; flex-direction: column; gap: 12px; } .worldPicker h2 { margin: 14px 0 0; color: #60758a; font-size: 14px; } .worldPicker button { border: 1px solid #d8e5f1; border-radius: 8px; background: #fff; padding: 13px; text-align: left; color: #1a2d3d; } .worldPicker button strong, .worldPicker button span { display: block; } .worldPicker button span { color: #667b90; line-height: 1.45; margin-top: 4px; } .worldPicker .selected { border-color: #43c5b8; background: #ebfbf7; } .worldPicker .small { display: flex; justify-content: space-between; align-items: center; gap: 10px; } .resetButton { margin-top: auto; text-align: center !important; background: #f5f8fc !important; }
.playColumn { padding: 22px; display: grid; gap: 16px; align-content: start; }
.questBanner, .firstRunCoach, .tokenShelf, .actionDock, .directorInput, .keepsake, .sparkGrid, .timeline, .testMode header, .scenarioGrid article, .gameplayChecks { border: 1px solid #d8e5f1; border-radius: 8px; background: #fff; padding: 16px; }
.questBanner { display: flex; justify-content: space-between; gap: 18px; align-items: center; } .questBanner span, .questBanner p { color: #667b90; margin: 0; } .questBanner h1 { margin: 4px 0 6px; font-size: 26px; line-height: 1.16; } .questMeter { min-width: 220px; display: grid; gap: 7px; } .questMeter strong { font-size: 28px; } .questMeter div { height: 14px; background: #e8f1f8; border-radius: 999px; overflow: hidden; } .questMeter i { display: block; height: 100%; background: linear-gradient(90deg, #43c5b8, #ff8c6a); }
.firstRunCoach { display: flex; align-items: center; justify-content: space-between; gap: 14px; background: #fff7e9; border-color: #ffd9a9; } .firstRunCoach p { margin: 5px 0 0; color: #52677c; } .firstRunCoach button, .directorInput button, .parentBook header button, .testMode header button, .scenarioGrid button { border: 0; border-radius: 8px; background: #ff8c6a; color: #fff; font-weight: 900; padding: 12px 16px; }
.worldStage { --sky: #8bd8ff; --ground: #95d987; --accent: #ff8c6a; min-height: 430px; position: relative; overflow: hidden; border: 1px solid rgba(23, 50, 77, 0.12); border-radius: 8px; background: linear-gradient(180deg, var(--sky) 0%, #f7fbff 62%, var(--ground) 63%, var(--ground) 100%); box-shadow: inset 0 -50px 90px rgba(23, 50, 77, 0.08); }
.skyOrb, .stageGround, .portalRing, .stageObject, .companionCard { position: absolute; } .skyOrb { right: 8%; top: 11%; width: 92px; height: 92px; border-radius: 50%; background: #ffd166; box-shadow: 0 0 0 18px rgba(255, 209, 102, 0.25); } .stageGround { left: -6%; right: -6%; bottom: -70px; height: 170px; border-radius: 55% 55% 0 0; background: rgba(255,255,255,.26); } .portalRing { left: 11%; top: 16%; width: 170px; height: 86px; border-radius: 999px; border: 14px solid rgba(255,255,255,.72); }
.stageObject { min-width: 96px; max-width: 150px; min-height: 56px; border: 2px solid rgba(23, 50, 77, 0.12); border-radius: 8px; background: rgba(255,255,255,.92); color: #17324d; font-weight: 900; box-shadow: 0 14px 28px rgba(23,50,77,.16); } .object1 { left: 12%; bottom: 84px; } .object2 { left: 33%; bottom: 138px; } .object3 { left: 54%; bottom: 88px; } .object4 { right: 14%; bottom: 150px; } .object5 { right: 9%; bottom: 72px; } .object6 { left: 20%; top: 105px; }
.companionCard { left: 24px; bottom: 24px; width: min(360px, calc(100% - 48px)); background: #17324d; color: #fff; border-radius: 8px; padding: 15px; box-shadow: 0 18px 36px rgba(23,50,77,.24); } .companionCard span { display: block; color: #d7eeff; line-height: 1.48; margin-top: 5px; }
.tokenShelf { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; } .tokenShelf strong, .tokenShelf span { display: block; } .tokenShelf span { margin-top: 5px; color: #60758a; }
.actionDock { display: grid; grid-template-columns: repeat(5, minmax(130px, 1fr)); gap: 12px; } .actionCard { min-height: 128px; border: 1px solid #d8e5f1; border-radius: 8px; background: #fbfdff; padding: 12px; text-align: left; display: grid; gap: 7px; align-content: start; } .actionCard small { color: #ff8c6a; font-weight: 900; text-transform: uppercase; } .actionCard strong { font-size: 17px; } .actionCard span { color: #60758a; line-height: 1.35; }
.directorInput { display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: 10px; } .directorInput input { border: 1px solid #cbd9e8; border-radius: 8px; min-height: 48px; padding: 0 14px; }
.parentBook, .testMode { padding: 24px; display: grid; gap: 16px; } .parentBook header, .testMode header { display: flex; justify-content: space-between; align-items: center; gap: 16px; } .parentBook h1, .testMode h1 { margin: 4px 0 0; font-size: 30px; } .parentBook span, .testMode span { color: #60758a; }
.keepsake { background: #fff8ed; border-color: #ffd8a8; } .sparkGrid { display: grid; gap: 12px; } .sparkGrid div { display: grid; grid-template-columns: 130px minmax(120px, 1fr) 48px; align-items: center; gap: 12px; } meter { width: 100%; height: 16px; }
.timeline { display: grid; gap: 12px; } .timeline article { border: 1px solid #e2edf6; border-radius: 8px; padding: 13px; background: #fbfdff; } .timeline p { margin: 8px 0; color: #3d5268; } .timeline small { color: #60758a; } .empty { color: #60758a; }
.scenarioGrid { display: grid; grid-template-columns: repeat(3, minmax(220px, 1fr)); gap: 14px; } .scenarioGrid article { display: grid; gap: 10px; } .scenarioGrid p { color: #52677c; margin: 0; line-height: 1.45; } .gameplayChecks { display: grid; gap: 8px; } .gameplayChecks h2 { margin: 0; } .gameplayChecks p { margin: 0; border: 1px solid #e2edf6; border-radius: 8px; padding: 10px; } .gameplayChecks .ok { background: #ecfbf7; border-color: #43c5b8; }
@media (max-width: 980px) { .gameBoard { grid-template-columns: 1fr; } .worldPicker { border-right: 0; border-bottom: 1px solid #dce8f3; } .actionDock, .scenarioGrid { grid-template-columns: repeat(2, minmax(150px, 1fr)); } .topHud { align-items: stretch; flex-direction: column; } }
@media (max-width: 620px) { .playColumn, .parentBook, .testMode, .worldPicker { padding: 14px; } .questBanner, .firstRunCoach, .parentBook header, .testMode header { align-items: stretch; flex-direction: column; } .tokenShelf, .directorInput, .sparkGrid div, .actionDock, .scenarioGrid { grid-template-columns: 1fr; } .worldStage { min-height: 480px; } }
"""


def _readme_md() -> str:
    return """# 火火兔 Spark 游戏化内测版

这是 KUN Control Plane 自主生成的游戏化 MVP。它不再是输入反馈演示，而是包含收集、合成、帮助、提问、任务进度、世界状态变化和家长火花册的可玩版本。

## 运行

```bash
npm install
npm run dev -- --host 127.0.0.1 --port 5178
```

## 验证

```bash
npm run build
npm run test:internal
npm run test:user-sim
```

## 当前范围

- 平板优先 Web/PWA，可继续接 Capacitor。
- 两个世界：彩虹造物岛、故事星球。
- 游戏循环：行动卡、收集物、合成、帮助角色、任务进度、Spark 记录。
- AI 使用安全沙盒内的模拟导演，后续可替换为 GPT-5.5 CLI adapter。
- 云端同步是本地模拟队列，真实儿童数据上传前必须再次确认。
"""
