"""Default KUN-native runners for runtime follow-up work.

These runners close the activation gap between the Control Plane creating Qi/Nuo
follow-up work and the daemon having a safe, default way to execute it.
"""

from __future__ import annotations

import hashlib
import json
from collections.abc import Sequence
from datetime import UTC, datetime
from typing import Literal

from kun.control_plane.runtime import ControlPlaneRunner, InMemoryControlPlane, WorkItemResult
from kun.control_plane.v6 import ArtifactRecord, CapabilityProfile, GateEvaluation, WorkItem


def _now() -> datetime:
    return datetime.now(UTC)


def _hash_payload(payload: object) -> str:
    return hashlib.sha256(
        json.dumps(payload, sort_keys=True, separators=(",", ":"), default=str).encode("utf-8")
    ).hexdigest()


def _slug(value: str) -> str:
    safe = [ch if ch.isalnum() or ch in {"-", "_"} else "-" for ch in value]
    return "".join(safe).strip("-")[:80] or "item"


def _artifact(
    *,
    work_item: WorkItem,
    created_by: str,
    support: str,
    payload: dict[str, object],
) -> ArtifactRecord:
    payload_hash = _hash_payload(payload)
    return ArtifactRecord(
        artifact_id=f"artifact-{_slug(created_by)}-{_slug(work_item.work_item_id)}-{payload_hash[:12]}",
        kind="report",
        path_or_uri=(
            f"control-plane://runtime-followup/{created_by}/"
            f"{work_item.mission_id}/{work_item.work_item_id}/{payload_hash[:12]}"
        ),
        content_hash=payload_hash,
        created_by=created_by,
        mission_id=work_item.mission_id,
        work_item_id=work_item.work_item_id,
        supports=[support, "runtime_followup", *work_item.recovery_refs],
        freshness="fresh",
        source_quality="primary",
    )


def _pass_gate(
    *,
    work_item: WorkItem,
    created_by: str,
    artifact: ArtifactRecord,
    signal: str,
) -> GateEvaluation:
    return GateEvaluation(
        gate_evaluation_id=f"gate-{_slug(created_by)}-{_slug(work_item.work_item_id)}",
        mission_id=work_item.mission_id,
        task_plan_version=work_item.task_plan_version,
        subject_ref=work_item.work_item_id,
        stage="governance",
        task_type="self_improvement",
        rubric_version="kun-v6-runtime-followup-v1",
        metric_pack_version="kun-v6-runtime-followup-v1",
        north_star_verdict="pass",
        result_quality=0.86,
        speed=0.72,
        cost=0.84,
        risk=0.18,
        evidence_quality=0.82,
        collaboration_quality=0.78,
        score_breakdown={"runtime_followup_executed": 1.0},
        thresholds={"result_quality": 0.8},
        evidence_refs=[artifact.artifact_id],
        artifact_refs=[artifact.artifact_id],
        source_freshness="fresh",
        responsibility_scope="kun_auto",
        confidence=0.82,
        next_action="continue",
        next_state="running",
        governance_signal=signal,
        created_by=created_by,
    )


class NuoRuntimeRepairRunner:
    """Execute Nuo repair/classification work generated by runtime safeguards."""

    runner_type: Literal["agent"] = "agent"
    runner_identity = "nuo-runtime-repair-runner"

    def __init__(self, *, control_plane: InMemoryControlPlane) -> None:
        self.control_plane = control_plane

    def can_run(self, work_item: WorkItem) -> bool:
        return work_item.owner == "nuo" and work_item.type in {"repair", "retest"}

    def run(self, work_item: WorkItem) -> WorkItemResult:
        if not self.can_run(work_item):
            return WorkItemResult(
                status="failed",
                summary="Nuo runtime repair runner only handles Nuo repair/retest follow-up work.",
                failure_category="tool_failure",
            )
        payload = {
            "schema": "kun-v6-nuo-runtime-repair-v1",
            "mission_id": work_item.mission_id,
            "work_item_id": work_item.work_item_id,
            "failed_skill_refs": list(work_item.skill_refs),
            "recovery_refs": list(work_item.recovery_refs),
            "classification": _nuo_classification(work_item),
            "automatic_actions": [
                "classified system/tool/environment condition before agent scoring",
                "kept recovery evidence attached for replay and rerun",
                "left original KUN capability judgment unpenalized until clean retest evidence exists",
            ],
            "rerun_policy": "eligible_after_environment_or_wrapper_repair",
            "default_agent_failure_counted": False,
        }
        artifact = _artifact(
            work_item=work_item,
            created_by=self.runner_identity,
            support="nuo_runtime_repair_report",
            payload=payload,
        )
        return WorkItemResult(
            status="done",
            summary="Nuo classified the runtime/preflight condition and preserved a clean retest path.",
            artifacts=[artifact],
            gate_evaluation=_pass_gate(
                work_item=work_item,
                created_by=self.runner_identity,
                artifact=artifact,
                signal="nuo_runtime_repair_executed",
            ),
        )


class QiRuntimeGovernanceRunner:
    """Execute Qi governance work generated by runtime learning signals."""

    runner_type: Literal["agent"] = "agent"
    runner_identity = "qi-runtime-governance-runner"

    def __init__(self, *, control_plane: InMemoryControlPlane) -> None:
        self.control_plane = control_plane

    def can_run(self, work_item: WorkItem) -> bool:
        return work_item.owner == "qi" and work_item.type == "governance"

    def run(self, work_item: WorkItem) -> WorkItemResult:
        if not self.can_run(work_item):
            return WorkItemResult(
                status="failed",
                summary="Qi runtime governance runner only handles Qi governance follow-up work.",
                failure_category="tool_failure",
            )
        decision = _qi_decision(work_item)
        payload = {
            "schema": "kun-v6-qi-runtime-governance-v1",
            "mission_id": work_item.mission_id,
            "work_item_id": work_item.work_item_id,
            "decision": decision,
            "source_refs": [work_item.work_item_id, *work_item.recovery_refs],
            "required_capability_refs": list(work_item.required_capability_refs),
            "runtime_default_policy": "replay_or_holdout_only_until_formal_promotion",
            "default_runtime_enabled": False,
            "next_stage": "replay" if decision in {"candidate", "merge"} else "review_only",
            "rollback_plan": [
                "do not enable by default until holdout, shadow, canary, and production gates pass",
                "remove or supersede this profile if future clean retests do not reproduce the signal",
            ],
        }
        artifact = _artifact(
            work_item=work_item,
            created_by=self.runner_identity,
            support="qi_runtime_governance_report",
            payload=payload,
        )
        profile_ref = None
        if decision in {"candidate", "merge"}:
            profile = CapabilityProfile(
                capability_id=f"cap-qi-runtime-{_slug(work_item.work_item_id)}",
                capability_name=f"Runtime learning from {work_item.work_item_id}",
                governance_key=f"runtime-learning:{_slug(work_item.work_item_id)}",
                source_refs=[work_item.work_item_id, *work_item.recovery_refs],
                source_versions=["runtime-followup-v1"],
                evidence_refs=[artifact.artifact_id],
                known_limits=[
                    "not production default until holdout/shadow/canary evidence exists",
                    "runtime follow-up artifacts are evidence, not automatic behavior changes",
                ],
                promotion_stage="replay",
                rollback_plan=[
                    "delete replay candidate or supersede with a cleaner profile if retests fail"
                ],
                runtime_enabled=False,
            )
            self.control_plane.capability_profiles[profile.capability_id] = profile
            if self.control_plane.store is not None:
                self.control_plane.store.put_capability_profile(profile)
            profile_ref = profile.capability_id
            artifact = artifact.model_copy(
                update={"supports": [*artifact.supports, profile.capability_id]}
            )
        gate = _pass_gate(
            work_item=work_item,
            created_by=self.runner_identity,
            artifact=artifact,
            signal=f"qi_runtime_governance_{decision}",
        )
        summary = "Qi recorded the runtime learning signal as governed evidence."
        if profile_ref:
            summary += f" Replay candidate: {profile_ref}."
        return WorkItemResult(
            status="done",
            summary=summary,
            artifacts=[artifact],
            gate_evaluation=gate,
        )


def _nuo_classification(work_item: WorkItem) -> str:
    text = f"{work_item.expected_output}\n{' '.join(work_item.skill_refs)}".lower()
    if any(token in text for token in ("timeout", "eof", "network", "auth", "wrapper")):
        return "environment_or_wrapper_condition"
    if any(token in text for token in ("stub", "fallback", "misrouting", "route")):
        return "pollution_or_routing_condition"
    if work_item.skill_refs:
        return "skill_preflight_condition"
    return "runtime_condition_requires_clean_retest"


def _qi_decision(work_item: WorkItem) -> str:
    text = work_item.expected_output.lower()
    if any(token in text for token in ("promote", "capability", "governance", "learning")):
        return "candidate"
    if any(token in text for token in ("merge", "dedupe", "duplicate")):
        return "merge"
    if any(token in text for token in ("delete", "remove", "discard")):
        return "discard"
        return "keep"


class ChainedControlPlaneRunner:
    """Try multiple specialized runners behind one owner route."""

    runner_type: Literal["agent"] = "agent"

    def __init__(self, *, runner_identity: str, runners: Sequence[ControlPlaneRunner]) -> None:
        self.runner_identity = runner_identity
        self.runners = list(runners)

    def can_run(self, work_item: WorkItem) -> bool:
        return self._runner_for(work_item) is not None

    def run(self, work_item: WorkItem) -> WorkItemResult:
        runner = self._runner_for(work_item)
        if runner is None:
            return WorkItemResult(
                status="failed",
                summary=f"No chained runner can execute {work_item.work_item_id}.",
                failure_category="tool_failure",
            )
        return runner.run(work_item)

    def _runner_for(self, work_item: WorkItem) -> ControlPlaneRunner | None:
        for runner in self.runners:
            can_run = getattr(runner, "can_run", None)
            if callable(can_run) and not can_run(work_item):
                continue
            return runner
        return None


__all__ = ["ChainedControlPlaneRunner", "NuoRuntimeRepairRunner", "QiRuntimeGovernanceRunner"]
